Repository mozilla/contain-facebook, pull requests merged in 2018-04, with the labels that each got.

#94 Remove cookies in all containers except in Facebook Container when initializing
  background.js
Labels: 1.3.0

#52 Add more facebook domains 45
  background.js
Labels: 1.3.0

#76 Maintain windowId
  background.js
Labels: 1.3.1

#110 fix #102: add cdn.fbsbx.com to container
  background.js
Labels: 1.3.1

#127 Send jailed domains
  src/background.js
Labels: 1.4.0

#130 Bump version for 1.4.0
  package-lock.json
  package.json
  src/background.js
  src/manifest.json
Labels: 1.4.0
